version: '3.7'
services:
  backend:
    container_name: laravel
    build:
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    environment:
      DB_HOST: db
      DB_DATABASE: dobroVlckovice
      DB_USERNAME: root
      DB_PASSWORD: Bublanina123
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    networks:
      - app

  frontend:
    container_name: react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app
  db:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'dobroVlckovice'
      MYSQL_USER: 'jachymp'
      MYSQL_PASSWORD: 'Brumbal888'
      MYSQL_ROOT_PASSWORD: 'Bublanina123'
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app

volumes:
  db-data: ~

networks:
  app:
    driver: bridge